version: 2
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:7.10.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run: npm run build
      - run: npm run test.unit.coverage
      - codecov/upload:
          file: ./coverage/lcov.info